# Generated by Django 4.2.1 on 2023-05-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='borrow_inventory',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='sell_inventory',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='sell_price',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['name'], name='book_book_name_3b5d59_idx'),
        ),
    ]
