# Generated by Django 4.2.1 on 2023-05-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='books',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='book.book'),
        ),
    ]
