# Generated by Django 4.2.1 on 2023-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
