# Generated by Django 4.2.1 on 2023-05-25 14:07

import book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[(book.models.Role['staff'], 'Staff'), (book.models.Role['member'], 'Member')], default=book.models.Role['member'], max_length=10),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('is_returned', models.BooleanField()),
                ('return_date', models.DateField(null=True)),
                ('status', models.CharField(choices=[(book.models.BookStatus['checkout'], 'CheckOut'), (book.models.BookStatus['hold'], 'Hold'), (book.models.BookStatus['sold'], 'Soled')], default=book.models.BookStatus['sold'], max_length=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.customuser')),
            ],
        ),
    ]
