# Generated by Django 4.2.1 on 2023-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_account_book_accoun_user_id_4be604_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['books'], name='book_catego_books_i_8bd574_idx'),
        ),
    ]
